### ISSUE TITLE
Tests fail with latest version of tap

### ISSUE THREAD

**Issue by es128** [thlorenz/readdirp#29]
@thlorenz [your prophecy](https://github.com/thlorenz/readdirp/pull/27#issuecomment-128877664) has already come to pass

With tap@1.3.2, tests pass, any higher and they fail (even the patch bumps).

Simplest solution would be to just lock the version. wdyt?

**Comment by es128** [comment]
I've narrowed it down to this commit in tap where the failure starts: https://github.com/isaacs/node-tap/commit/7fa8df4dfc6b010f7f1affebe9a37633a250a190

Which would imply there may actually be a deeper problem with the tests - that there were some failures (or timing problems) that were being ignored silently.

**Comment by toddself** [comment]
I'm trying to dive into this to land my change for adding pause/resume to the stream.

Taking this apart a few questions -- 

1. When I disable all the tests except the first test, it fails because it is expecting 12 files, but it gets 18 files in the return.  It seems to be emitting several files twice — if I log out each entry in `test/readdirp-stream.js` I get the following output: 
```
/Users/todd/src/readdirp/test/bed/link.ext1
/Users/todd/src/readdirp/test/bed/root_file1.ext1
/Users/todd/src/readdirp/test/bed/root_file2.ext2
/Users/todd/src/readdirp/test/bed/root_file3.ext3
/Users/todd/src/readdirp/test/bed/root_dir2/root_dir2_file1.ext1
/Users/todd/src/readdirp/test/bed/root_dir2/root_dir2_file2.ext2
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file1.ext1
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file2.ext2
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file3.ext3
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file1.ext1
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file2.ext2
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file3.ext3
/Users/todd/src/readdirp/test/bed/root_dir2/root_dir2_subdir1/.gitignore
/Users/todd/src/readdirp/test/bed/root_dir2/root_dir2_subdir2/.gitignore
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_subdir1/root1_dir1_subdir1_file1.ext1
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_subdir2/.gitignore
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_subdir1/root1_dir1_subdir1_file1.ext1
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_subdir2/.gitignore
```

For some reason this is emitting the following files twice:
```
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file1.ext1
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file2.ext2
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_file3.ext3
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_subdir1/root1_dir1_subdir1_file1.ext1
/Users/todd/src/readdirp/test/bed/root_dir1/root_dir1_subdir2/.gitignore
/Users/todd/src/readdirp/test/bed/root_dir2/root_dir2_subdir1/.gitignore
```

But not others.

2. If I add a `t.end()` to the wrapped `test` scope, it no longer complains about tests not completing. However, is there a reason that the tests in each file are wrapped in a test themselves?
3. Is there a reason to use node to invoke each test independently rather than using `tap test/*js`?

**Comment by thlorenz** [comment]
Fixed in master
